### ISSUE TITLE
Padanan kata tidak sesuai

### ISSUE THREAD

**Issue by llohanda** [adhikasp/rendra#1]
Aku sebenarnya belum cek semua, tapi dalam daftar padanan kata, ada satu yang mengganjal.

Kata `bug` padanan resminya adalah _galat_, bukan _kutu_. Dengan demikian, kata `debug` bisa diterjemahkan sebagai _penyelesaian galat_.

Terima kasih atas perhatiannya ^^ kalau ada padanan kata lain yang perlu diberi perhatian khusus, akan saya beritahukan lagi.

**Comment by adhikasp** [comment]
Yup, sebenarnya masih ada beberapa kata yang tidak sesuai juga, padahal sumbernya ini mengambil dari data pemerintah. Penerjemahan istilah IT Inggris sepertinya susah-susah gampang :/

Anyway terimakasih laporannya 👍
